version: '3'

services:
  db:
    container_name: db_node_aragamble_local
    image: mongo:5.0.9
    ports:
      - "${MONGO_PORT}:27017"
    env_file: .env
    networks:
      # - outer_aragamble_network
      - default
    volumes:
        - studapi_aragamble_loc:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aragamble_local
      ME_CONFIG_MONGODB_ADMINPASSWORD: aragamble
      ME_CONFIG_MONGODB_URL: mongodb://aragamble_local:aragamble@db:27017/
  redis:
    image: redis:6.2.1-alpine
    ports: 
      - "6379:6379"
  # flower:
  #   image: mher/flower:0.9.7
  #   command: "flower --port=5555 --broker=redis://redis:6379/0 --basic_auth=user1:password1" 
  #   networks:
  #     - outer_tmsis_network
  #     - default
  #   ports: 
  #     - "5555:5555"
  # memcached:
  #   image: memcached:1.6.9-alpine
  #   networks:
  #     - outer_tmsis_network
  #     - default
  #   ports: 
  #     - "11211:11211"
  # memcached_admin:
  #   image:  jacksoncage/phpmemcachedadmin:latest
  #   networks:
  #     - outer_tmsis_network
  #     - default
  #   ports: 
  #     - "8080:80"
volumes:
    studapi_aragamble_loc:
# networks: 
#   default:
#     driver: bridge
#   outer_aragamble_network:
#     external: true