version: '3'

services:
  db:
    container_name: db_node_aragamble_local
    image: mongo:5.0.9
    ports:
      - "${MONGO_PORT}:27017"
    env_file: .env
    networks:
      # - outer_aragamble_network
      - default
    volumes:
        - studapi_aragamble_loc:/data/db
  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aragamble_local
      ME_CONFIG_MONGODB_ADMINPASSWORD: aragamble
      ME_CONFIG_MONGODB_URL: mongodb://aragamble_local:aragamble@db:27017/
  redis:
    image: redis:6.2.1-alpine
    ports: 
      - "6379:6379"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    ports:
      - '9000:9000'
    environment:
      - HTTP_PORT=9000
    depends_on:
      - zookeeper
  # flower:
  #   image: mher/flower:0.9.7
  #   command: "flower --port=5555 --broker=redis://redis:6379/0 --basic_auth=user1:password1" 
  #   networks:
  #     - outer_tmsis_network
  #     - default
  #   ports: 
  #     - "5555:5555"
  # memcached:
  #   image: memcached:1.6.9-alpine
  #   networks:
  #     - outer_tmsis_network
  #     - default
  #   ports: 
  #     - "11211:11211"
  # memcached_admin:
  #   image:  jacksoncage/phpmemcachedadmin:latest
  #   networks:
  #     - outer_tmsis_network
  #     - default
  #   ports: 
  #     - "8080:80"
volumes:
    studapi_aragamble_loc:
# networks: 
#   default:
#     driver: bridge
#   outer_aragamble_network:
#     external: true